### ISSUE TITLE
Not every annotation is created?

### ISSUE THREAD

**Issue by frottke** [equisoft-actions/sarif-annotator#183]
I use your action in this form:

```
- name: Create annotations
  uses: equisoft-actions/sarif-annotator@v1.2.2
  with:
    level: warning
    limit: "500"
    sarif-path: results.sarif
    title: PSScriptAnalyzer results
```

It looks like only 14 annotations are being created. I know, because of the output of the action that there are 189 entries in the sarif file. Which are in the log output of "Create annotations".Is there something missing in my yaml? 

Also one more issue. Four of these 14 annotations are errors. But the step is still successful, is there a way to fail the step at the end? I want to use this action as an pull request check.

Thank you in advance 👍
